# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'TeamPayroll' do

pod 'FMDB'
pod 'SDWebImage', '~> 3.7'
pod 'UIColor-ColorWithHexAndAlpha', '~> 1.2'

end

target 'TeamPayrollTests' do

end

